library(preprocessCore)
dt<-read.table('data/miRNA_expression.out',header=T,row.names=1)
m <- as.matrix(dt)
n <- normalize.quantiles(m,copy=TRUE)
dt2<-data.frame(rownames(dt),n)
colnames(dt2)<-c("ID",colnames(dt))
write.table(dt2,'data/miRNA_expression.out.norm',sep='\t',quote=F, row.names=F)

dt<-read.table('data/gene_expression.out',header=T,row.names=1)
m <- as.matrix(dt)
n <- normalize.quantiles(m,copy=TRUE)
dt2<-data.frame(rownames(dt),n)
colnames(dt2)<-c("ID",colnames(dt))
write.table(dt2,'data/gene_expression.out.norm',sep='\t',quote=F, row.names=F)
